select 'Total Sales' as measure_name, SUM(sales_amount) as measure_value FROM gold.fact_sales
UNION ALL
select 'Total Quantity' as measure_name, SUM(quantity) from gold.fact_sales
UNION ALL
select 'Average Price', AVG(price) as average_price from gold.fact_sales
UNION ALL
select 'Total Nr. Orders', COUNT(DISTINCT order_number) from gold.fact_sales
UNION ALL
select 'Total Nr. Products', COUNT(DISTINCT(product_name)) from gold.dim_products
UNION ALL
select 'Total Nr. Customers', COUNT(customer_key) from gold.dim_customers

-- Find total customers by countries
select country, count(customer_key) as total_customers from gold.dim_customers
group by country
order by total_customers DESC

-- Find total customers by gender
select gender, count(customer_key) as total_customers from gold.dim_customers
group by gender
order by total_customers DESC
-- Find total products by category
select category, count(product_id) as total_products 
from gold.dim_products
group by category
order by total_products DESC
-- What is the average costs in each category?
select 
category,
AVG(cost) as avg_costs
from gold.dim_products
group by category
order by avg_costs desc

-- What is the total revenue generated for each category?

select gm.category, SUM(gs.sales_amount) as total_revenue from gold.fact_sales gs
left join gold.dim_products gm
on gm.product_key = gs.product_key
WHERE gm.product_key IS NOT NULL
group by gm.category
order by SUM(gs.sales_amount) DESC

-- Find total revenue is generated by each customer

select 
gc.customer_key,
gc.first_name,
gc.last_name,
SUM(gs.sales_amount) as total_revenue 
from gold.fact_sales gs
left join gold.dim_customers gc
on gc.customer_key = gs.customer_key
group by gc.customer_key,gc.first_name, gc.last_name
order by total_revenue desc

-- What is the distribution of sold items across countries?

select
gc.country,
SUM(gs.quantity) as total_sold
from gold.fact_sales gs
left join gold.dim_customers gc
on gc.customer_key = gs.customer_key
group by gc.country
order by total_sold desc

-- Which 5 products generate the highest revenue?
select top 5 gm.product_name, SUM(gs.sales_amount) as total_revenue from gold.fact_sales gs
left join gold.dim_products gm
on gm.product_key = gs.product_key
WHERE gm.product_key IS NOT NULL
group by gm.product_name
order by SUM(gs.sales_amount) DESC

select *
from (
		select gm.product_name, 
		SUM(gs.sales_amount) as total_revenue,
		ROW_number () over (ORDER BY SUM(gs.sales_amount) desc) as rank_products
		from gold.fact_sales gs
		left join gold.dim_products gm
		on gm.product_key = gs.product_key
		WHERE gm.product_key IS NOT NULL
		group by gm.product_name
			) t 
		where rank_products <=5

-- What are the 5 worst-performing products in terms of sales?

select *
from 
(
	select top 5 gm.product_name, 
	SUM(gs.sales_amount) as total_revenue, 
	ROW_number () over (ORDER BY sum(gs.sales_amount) asc) as rank_products
	from gold.fact_sales gs
	left join gold.dim_products gm
	on gm.product_key = gs.product_key
	WHERE gm.product_key IS NOT NULL
	group by gm.product_name
)t
where rank_products <=5

